--- 
services: 
  mysql-server: 
    environment: 
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:latest"
    restart: always
    volumes: 
      - "mysql-data:/var/lib/mysql"
  phpmyadmin: 
    environment: 
      PMA_HOST: mysql-server
      PMA_PASSWORD: password
      PMA_USER: root
      UPLOAD_LIMIT: 1G
    image: "phpmyadmin/phpmyadmin:latest"
    ports: 
      - "5000:80"
    restart: always
  web-server: 
    build: 
      context: "."
      dockerfile: php.Dockerfile
    ports: 
      - "8080:80"
    restart: always
    volumes: 
      - "./html/:/var/www/html/"
version: "3.3"
volumes: 
  mysql-data:

